export const employee = {
  id: "EMP1001",
  name: "Sanjana N",
  designation: "Software Engineer",
  department: "Development",
  location: "Mysore",
  joiningDate: "8 JULY 2026",
//   image:
//     "https://i.pravatar.cc/150?img=12",
};

export const summary = {
  present: 21,
  leave: 3,
  absent: 2,
  halfDay: 1,
  weeklyOff: 8,
  totalDays: 31,
};

export const attendanceRows = [
  {
    day: 1,
    status: "Present",
    inTime: "09:00",
    outTime: "18:00",
    workingHours: "9",
    otHours: "0",
    remarks: "",
  },
  {
    day: 2,
    status: "Present",
    inTime: "09:00",
    outTime: "18:00",
    workingHours: "9",
    otHours: "0",
    remarks: "",
  },
  {
    day: 3,
    status: "Leave",
    inTime: "-",
    outTime: "-",
    workingHours: "0",
    otHours: "0",
    remarks: "Leave",
  },
  {
    day: 4,
    week: "Sat",
    status: "WO",
    inTime: "-",
    outTime: "-",
    workingHours: "-",
    otHours: "-",
    remarks: "",
  },
  {
    day: 5,
    week: "Sun",
    status: "WO",
    inTime: "-",
    outTime: "-",
    workingHours: "-",
    otHours: "-",
    remarks: "",
  },
  {
    day: 6,
    week: "Mon",
    status: "L",
    inTime: "-",
    outTime: "-",
    workingHours: "-",
    otHours: "-",
    remarks: "CL",
  },
  {
    day: 7,
    week: "Tue",
    status: "P",
    inTime: "09:00",
    outTime: "18:00",
    workingHours: "9.00",
    otHours: "-",
    remarks: "",
  },
];

